#:kivy 2.3.1
#:import dp kivy.metrics.dp

<CardWidget>:
    MDBoxLayout:
        orientation: 'vertical'
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        padding: dp(8)
        spacing: dp(4)
        
        MDLabel:
            text: root.title
            theme_text_color: "Custom"
            text_color: 0, 0, 0, 1  # Noir
            halign: 'left'
            bold: True
            font_size: "18sp"
            
        MDLabel:
            text: root.description
            theme_text_color: "Custom"
            text_color: 0, 0, 0, 0.87  # Noir avec légère transparence
            halign: 'left'
            font_size: "14sp"
        
<ScrollScreen>:
    MDScrollView:
        size_hint: 1, 1
        scroll_type: ['bars']
        bar_width: "20dp"
        MDBoxLayout:
            id: card_container
            orientation: 'vertical'
            size_hint_y: None
            height: self.minimum_height
            spacing: "8dp"
            padding: ["8dp", "8dp", "28dp", "8dp"]  # gauche, haut, droite, bas
